// Executed SQL in an ephemeral PostgreSQL engine; never a production migration.
const {PGlite}=require(process.argv[2] || '@electric-sql/pglite');
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
(async()=>{
 const db=new PGlite();
 await db.exec(`create role anon;create role authenticated;create role service_role;
 create table users(id uuid primary key,role text);
 create table analyses(id uuid primary key,user_id uuid,response_json jsonb);`);
 const migration=n=>fs.readFileSync(path.join(__dirname,'../deploy-vps/migrations/'+n),'utf8');
 await db.exec(migration('001_contour_workflow.sql'));
 await db.exec(migration('003_model_quality.sql'));
 const id=n=>`00000000-0000-4000-8000-${String(n).padStart(12,'0')}`;
 const admin=id(1),user=id(2),analysis=id(3),snapshot=id(4),job=id(5),lease=id(6);
 await db.query('insert into users values ($1, $2), ($3, $4)',[admin,'admin',user,'user']);
 const call=async(action,key,actor=admin,data={})=>(await db.query(
   'select ml_transition($1,$2,$3,$4) r',[action,key,actor,data])).rows[0].r;
 await assert.rejects(call('snapshot',snapshot,user,{model_type:'segmentation',manifest:{}}));
 const snap={model_type:'segmentation',manifest:{synthetic_test:true}};
 assert.deepEqual(await call('snapshot',snapshot,admin,snap),await call('snapshot',snapshot,admin,snap));
 await assert.rejects(call('snapshot',snapshot,admin,{...snap,model_type:'classification'}));
 await db.query('select contour_transition($1,$2,$3,$4,$5)', ['register',user,'fixture',analysis,'a'.repeat(64)]);
 const label={owner_id:user,analysis_id:analysis,correction_id:'fixture',image_sha256:'a'.repeat(64),label:{confirmed:true,rank:'species',scientific_name:'Test species'}};
 assert.deepEqual(await call('label',id(7),admin,label),await call('label',id(7),admin,label));
 await assert.rejects(call('label',id(7),admin,{...label,owner_id:admin}));
 await call('label',id(8),admin,{...label,parent_id:id(7)});
 await assert.rejects(call('label',id(9),admin,{...label,parent_id:id(7)}));
 assert.equal((await db.query('select status from contour_revisions')).rows[0].status,'draft');
 const request={snapshot_id:snapshot,params:{epochs:1}};
 assert.deepEqual(await call('enqueue',job,admin,request),await call('enqueue',job,admin,request));
 await assert.rejects(call('enqueue',job,admin,{...request,params:{epochs:2}}));
 await assert.rejects(call('enqueue',id(10),admin,request));
 assert.equal((await call('claim',lease,null)).id,job);
 await assert.rejects(call('heartbeat',job,null,{lease_id:id(11)}));
 assert.equal((await call('cancel',job)).state,'cancel_requested');
 await assert.rejects(call('finish',job,null,{lease_id:lease,state:'completed',progress:{},model:{}}));
 assert.equal((await call('finish',job,null,{lease_id:lease,state:'cancelled',progress:{}})).state,'cancelled');
 assert.equal((await db.query('select count(*)::int n from ml_models')).rows[0].n,0);
 await call('enqueue',id(10),admin,request);
 await call('claim',id(11),null);
 await db.query("update ml_jobs set lease_until=now()-interval '1 second' where id=$1",[id(10)]);
 assert.equal(await call('claim',id(12),null),null);
 assert.equal((await db.query('select state from ml_jobs where id=$1',[id(10)])).rows[0].state,'failed');
 await assert.rejects(call('finish',id(10),null,{lease_id:id(11),state:'completed',progress:{},model:{}}));
 await call('enqueue',id(13),admin,request); await call('claim',id(14),null);
 await call('finish',id(13),null,{lease_id:id(14),state:'completed',progress:{},model:{compatible:true,eligible_for_activation:true}});
 assert.equal((await call('finish',id(13),null,{lease_id:id(14),state:'completed',progress:{},model:{compatible:true,eligible_for_activation:true}})).state,'completed');
 await assert.rejects(call('finish',id(13),null,{lease_id:id(14),state:'failed',progress:{}}));
 // Finishing does not activate. Switching is a separate CAS operation.
 assert.equal((await db.query("select model_id from ml_active_models where model_type='segmentation'")).rows[0].model_id,null);
 await assert.rejects(call('activate',id(13),user,{expected_generation:0}));
 await assert.rejects(call('activate',id(13),admin,{}));
 assert.equal((await call('activate',id(13),admin,{expected_generation:0})).generation,1);
 await assert.rejects(call('activate',null,admin,{expected_generation:0}));
 const rollback=await call('activate',null,admin,{expected_generation:1});
 assert.equal(rollback.model_id,null);assert.equal(rollback.history.length,2);
 await db.exec(migration('003_model_quality.sql'));
 assert.equal((await db.query('select count(*)::int n from ml_jobs')).rows[0].n,3);
 await db.exec('set role authenticated');
 await assert.rejects(db.query('select * from ml_jobs'));
 await assert.rejects(call('claim',id(15),null));
 await db.exec('reset role');
 assert.equal((await db.query('select model_quality_version() n')).rows[0].n,1);
 await db.close();
 console.log('PASS: PostgreSQL execution: ACL, independent labels, retries/conflicts, leases, cancellation, registry CAS/rollback, migration rerun. Synthetic fixtures only.');
})().catch(e=>{console.error(e);process.exit(1)});
